version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: taskdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis
    ports:
      - "6378:6379"

  api:
    build: .
    environment:
      DATABASE_URL: "mysql://root:rootpassword@mysql:3306/taskdb"
      REDIS_URL: "redis://redis:6379"
      NODE_ENV: docker
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - redis

volumes:
  mysql_data:
